apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:masters\n  rolearn: arn:aws:iam::470134764101:role/UdacityFlaskDeployCBKubectlRole\n
    \ username: build \n- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn:
    arn:aws:iam::470134764101:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-GZSIA89L8A0J\n
    \ username: system:node:{{EC2PrivateDNSName}}\n"
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-09T10:53:14Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-04-09T10:53:14Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-patch
    operation: Update
    time: "2021-04-09T11:18:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5812"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2b058b47-f233-4d0b-827f-6dc0f8034ee1
